get:
  tags:
    - catalog
  summary: Get a list of all available services
  responses:
    '200':
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                required: 
                  - services
                properties:
                  services:
                    $ref: "../../schemas/catalog/Services.yaml"
    default:
      $ref: "../../responses/Error.yaml"
post:
  tags:
    - catalog
  summary: Create catalog service
  security:
    - bearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - name
          properties:
            name:
              type: string
            parent_id:
              type: integer
  responses:
    '201':
      content:
        application/json:
          schema:
            type: object
            required:
              - data
            properties:
              data:
                type: object
                required: 
                  - objects
                properties:
                  objects:
                    $ref: "../../schemas/catalog/Service.yaml"
    default:
      $ref: "../../responses/Error.yaml"
