version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ubrato-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ubrato"

  typesense:
    image: typesense/typesense:26.0-amd64
    container_name: ubrato-typesense
    restart: on-failure
    ports:
      - "8108:8108"
    command: '--data-dir /data --api-key=xyz --enable-cors'

  typesense-web:
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    container_name: typesense-web
    restart: on-failure
    ports:
      - "3003:80"
    volumes:
      - ./typesense-config.json:/srv/config.json

  service-nats:
    container_name: service-nats
    image: nats:2.10.14-alpine3.19
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "--name=service-nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
