openapi: 3.0.3
servers:
  - description: local
    url: /
  - description: dev
    url: https://api.ubrato.ru
info:
  title: Ubrato core
  description: ubrato core oas
  version: 1.0.0
paths:
  /v1/auth/signin:
    $ref: "./v1/paths/auth/signin.yaml"
  /v1/auth/signup:
    $ref: "./v1/paths/auth/signup.yaml"
  /v1/auth/user:
    $ref: "./v1/paths/auth/user.yaml"
  /v1/auth/refresh:
    $ref: "./v1/paths/auth/refresh.yaml"
  /v1/tenders/create:
    $ref: "./v1/paths/tenders.yaml"
  # /v1/auth/confirm-email:
  #   $ref: "./v1/paths/auth/confirm-email.yaml"
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: ubrato_session
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT